name: Deploys the published docker image to railway

on:
  push:
    branches:
      - master

jobs:
  quality-gate:
    uses: ./.github/workflows/pull-request.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy-docker-image:
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:

    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo 'export PATH="$HOME/.railway/bin:$PATH"' >> $GITHUB_ENV

    - name: Set Railway Token
      run: echo "RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}" >> $GITHUB_ENV

    - name: Deploy Docker Image to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        railway redeploy --service devops --yes
