name: Deploys the published docker image to railway

on:
  push:
    branches:
      - master

jobs:
  quality-gate:
    uses: ./.github/workflows/pull-request.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  deploy-docker-image:
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:
    - name: Login to Railway
      run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy docker image
      run: railway up --service devops --image valkata7/devops:latest
