name: Initial project setup

on: [workflow_call]

jobs:
  initial_setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: devops

      - name: Set up node
        uses: actions/setup-node@v4