name: Primary Workflow

on:
  push:
    branches:
      - master

jobs:
  sast-scan:
    uses: ./.github/workflows/sast-scan.yml
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  quality_assurance:
    uses: ./.github/workflows/quality-assurance.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml
    needs: quality_assurance
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
