name: Primary workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  initial_setup:
    uses: ./.github/workflows/initial_setup.yml

  quality_assurance:
    needs: initial_setup
    uses: ./.github/workflows/quality_assurance.yml
