name: Primary Workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  quality_assurance:
    uses: ./.github/workflows/quality_assurance.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
