name: Primary Workflow

on:
  push:
    branches:
      - master

jobs:
  pull_request:
    uses: ./.github/workflows/pull-request.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  build-docker-image:
    uses: ./.github/workflows/build-docker-image.yml
    needs: pull_request
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
