name: Pull request workflow

on: [pull_request] 

jobs:
  initial_setup:
    uses: .github/workflows/initial_setup.yml@main

  quality_assurance:
    needs: initial_setup
    uses: .github/workflows/quality_assuarance.yml@main
