name: Code Quality Assurance

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  quality_assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Add .env file
        env:
          PORT: ${{ env.PORT }}
        run: |
          echo "PORT=${PORT}" >> .env

      - name: Run tests
        run: npm run test

      - name: Run lint
        run: npm run lint

      - name: Run SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v4
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
